init:
  - git config --global core.autocrlf true
branches:
  only:
    - master
    - dev
build_script:
- ps: .\build.ps1 -Target "build-all"
clone_depth: 1
test: off
deploy: off
os: Visual Studio 2017