language: csharp
matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx
      osx_image: xcode8.3
addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g

mono: 5.4.1
dotnet: 2.1.300
services:
  - docker

install:
  - nvm install 8.6.0
  - nvm use 8.6.0

branches:
  only:
    - master
    - dev
script:
  - if test "$TRAVIS_OS_NAME" == "osx"; then ./build.sh --target=ci ; fi
  - if test "$TRAVIS_OS_NAME" == "linux"; then ./build-linux.sh --target=ci ; fi

cache:
  directories:
  - /home/travis/.nuget/packages
