apiVersion: v1
kind: Endpoints
metadata:
  name: local-glusterfs 
subsets:
  - addresses:
      - ip: 192.168.1.74
    ports:
      - port: 24007
        name: glusterd
  - addresses:
      - ip: 192.168.1.75
    ports:
      - port: 24007
        name: glusterd