apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-gfs
  annotations:
    pv.beta.kubernetes.io/gid: "590" 
spec:
  capacity:
    storage: 2Gi 
  accessModes: 
    - ReadWriteMany
  glusterfs:
    endpoints: local-glusterfs
    path: gv0
    readOnly: false
  persistentVolumeReclaimPolicy: Retain