apiVersion: v1
kind: ConfigMap
metadata:
  name: web-config
data:
  appsettings.json: |-
    {
        "sqliteConnectionString": "Data Source=/club-data/dotnetclub.db",
        "Logging": {
          "LogLevel": {
            "Discussion": "Information",
            "Default": "Warning"
          },
          "PathFormat": "logs/log-{Date}.log",
          "FileSizeLimitBytes": 20971520,
          "OutputTemplate": "[{Level:u3}] {Timestamp:o} {SourceContext} {TraceId}{NewLine}  {Message} {NewLine}{Exception}"
        },
        "DataProtectionOptions": {
          "DisableAutomaticKeyGeneration" : true,
          "KeyRepositoryPath": "/data-protection-keys/",
          "ApplicationName": "dotnetclub"
        }
    }